const m = (p) => new URL(p, import.meta.url).href;

export const CHANNELS = [
  { id: 'synthwave', name: 'Synthwave Drive', module: m('./synthwave.js') },
  { id: 'aquarium', name: 'Midnight Aquarium', module: m('./aquarium.js') },
  { id: 'radar', name: 'Weather Radar', module: m('./radar.js') },
  { id: 'weatherfactory', name: 'Weather Factory', module: m('./weatherfactory.js') },
  { id: 'pocketplanet', name: 'Pocket Planet Weather', module: m('./pocketplanet.js') },
  { id: 'mechanisms', name: 'Satisfying Mechanisms', module: m('./mechanisms.js') },
  { id: 'bughotel', name: 'Bug Hotel Live', module: m('./bughotel.js') },
  { id: 'typespecimen', name: 'Type Specimen Theatre', module: m('./typespecimen.js') },
  { id: 'cozycompiler', name: 'The Cozy Compiler', module: m('./cozycompiler.js') },
  { id: 'lava', name: 'Lava Lamp', module: m('./lava.js') },
  { id: 'news', name: '24/7 Odd News', module: m('./news.js') },
  { id: 'musictheory', name: 'The 3-Minute Music Theory', module: m('./musictheory.js') },
  { id: 'tinyorch', name: 'Tiny Orchestra Workshop', module: m('./tinyorchestra.js') },
  { id: 'minutemuseum', name: 'Minute Museum', module: m('./minutemuseum.js') },
  { id: 'bonsai', name: 'Bonsai Time Machine', module: m('./bonsai.js') },
  { id: 'matrix', name: 'Terminal Rain', module: m('./matrix.js') },
  { id: 'retroboot', name: 'Retro Boot Sequence', module: m('./retroboot.js') },
  { id: 'orbits', name: 'Orbital Desktoy', module: m('./orbits.js') },
  { id: 'planetpost', name: 'Planetarium Postcards', module: m('./planetpostcards.js') },
  { id: 'oceanpost', name: 'Ocean Floor Postcards', module: m('./oceanpostcards.js') },
  { id: 'city', name: 'Pixel City Nights', module: m('./city.js') },
  { id: 'fire', name: 'Cozy Fireplace', module: m('./fireplace.js') },
  { id: 'flow', name: 'Flow Field', module: m('./flowfield.js') },
  { id: 'signalgarden', name: 'Analog Signal Garden', module: m('./signalgarden.js') },
  { id: 'lostmanual', name: 'The Lost Instruction Manual', module: m('./lostmanual.js') },
  { id: 'midnightlibrary', name: 'Midnight Library Index', module: m('./midnightlibrary.js') },
  { id: 'weatheredatlas', name: "Mapmaker's Weathered Atlas", module: m('./weatheredatlas.js') },
  { id: 'sports', name: 'Sportsboard 3000', module: m('./sports.js') },
  { id: 'kaleido', name: 'Kaleidoscope', module: m('./kaleido.js') },
  { id: 'spacecam', name: 'Deep Space Cam', module: m('./spacecam.js') },
  { id: 'shop', name: 'HyperMall Live', module: m('./shop.js') },
  { id: 'cctv', name: 'CCTV Night Watch', module: m('./cctv.js') },
  { id: 'slime', name: 'Slime Lab', module: m('./slime.js') },
  { id: 'kitchen', name: 'Kitchen Science Club', module: m('./kitchenscience.js') },
  { id: 'duckdebug', name: 'Rubber Duck Debugging', module: m('./rubberduck.js') },
  { id: 'onetool', name: 'One Tool, Ten Uses', module: m('./onetool.js') },
  { id: 'micromyst', name: 'Micro-Mysteries', module: m('./micromystery.js') },
  { id: 'traveldesk', name: 'The Tiny Travel Desk', module: m('./traveldesk.js') },
  { id: 'fixit', name: 'Fix-It ASMR', module: m('./fixit.js') },
  { id: 'patents', name: "History's Weird Patents", module: m('./weirdpatents.js') },
  { id: 'futurearch', name: 'Future Archaeology', module: m('./futurearch.js') },
  { id: 'circsafari', name: 'Circuit Safari', module: m('./circuitsafari.js') },
  { id: 'speedcook', name: 'Speed-Run Cooking', module: m('./speedcook.js') },
  { id: 'coffeetimer', name: 'Coffee Timer Radio', module: m('./coffeetimer.js') },
  { id: 'rainradio', name: 'Rainy Window Radio', module: m('./rainradio.js') },
  { id: 'ufohotline', name: 'Small Town UFO Hotline', module: m('./ufohotline.js') },
  { id: 'origami', name: 'Origami After Hours', module: m('./origami.js') },
  { id: 'tidydesk', name: 'Tidy Desk Reset', module: m('./tidydesk.js') },
  { id: 'workclock', name: 'Minimalist Workout Clock', module: m('./workoutclock.js') },
  { id: 'robotzoo', name: 'Robot Petting Zoo', module: m('./robotzoo.js') },
  { id: 'foleylab', name: 'Studio Foley Lab', module: m('./foleylab.js') },
  { id: 'timetable', name: 'Railway Timetable ASMR', module: m('./timetable.js') },
  { id: 'subwaystories', name: 'Subway Map Stories', module: m('./subwaystories.js') },
  { id: 'miniworlds', name: 'Found Footage: Miniature Worlds', module: m('./miniworlds.js') },
];
