export const CHANNELS = [
  { id: 'synthwave', name: 'Synthwave Drive', file: 'synthwave.js' },
  { id: 'aquarium', name: 'Midnight Aquarium', file: 'aquarium.js' },
  { id: 'radar', name: 'Weather Radar', file: 'radar.js' },
  { id: 'weatherfactory', name: 'Weather Factory', file: 'weatherfactory.js' },
  { id: 'pocketplanet', name: 'Pocket Planet Weather', file: 'pocketplanet.js' },
  { id: 'mechanisms', name: 'Satisfying Mechanisms', file: 'mechanisms.js' },
  { id: 'bughotel', name: 'Bug Hotel Live', file: 'bughotel.js' },
  { id: 'typespecimen', name: 'Type Specimen Theatre', file: 'typespecimen.js' },
  { id: 'cozycompiler', name: 'The Cozy Compiler', file: 'cozycompiler.js' },
  { id: 'lava', name: 'Lava Lamp', file: 'lava.js' },
  { id: 'news', name: '24/7 Odd News', file: 'news.js' },
  { id: 'musictheory', name: 'The 3-Minute Music Theory', file: 'musictheory.js' },
  { id: 'tinyorch', name: 'Tiny Orchestra Workshop', file: 'tinyorchestra.js' },
  { id: 'minutemuseum', name: 'Minute Museum', file: 'minutemuseum.js' },
  { id: 'bonsai', name: 'Bonsai Time Machine', file: 'bonsai.js' },
  { id: 'matrix', name: 'Terminal Rain', file: 'matrix.js' },
  { id: 'retroboot', name: 'Retro Boot Sequence', file: 'retroboot.js' },
  { id: 'obsoletemedia', name: 'Museum of Obsolete Media', file: 'obsoletemedia.js' },
  { id: 'orbits', name: 'Orbital Desktoy', file: 'orbits.js' },
  { id: 'planetpost', name: 'Planetarium Postcards', file: 'planetpostcards.js' },
  { id: 'oceanpost', name: 'Ocean Floor Postcards', file: 'oceanpostcards.js' },
  { id: 'city', name: 'Pixel City Nights', file: 'city.js' },
  { id: 'fire', name: 'Cozy Fireplace', file: 'fireplace.js' },
  { id: 'flow', name: 'Flow Field', file: 'flowfield.js' },
  { id: 'signalgarden', name: 'Analog Signal Garden', file: 'signalgarden.js' },
  { id: 'lostmanual', name: 'The Lost Instruction Manual', file: 'lostmanual.js' },
  { id: 'midnightlibrary', name: 'Midnight Library Index', file: 'midnightlibrary.js' },
  { id: 'weatheredatlas', name: "Mapmaker's Weathered Atlas", file: 'weatheredatlas.js' },
  { id: 'sports', name: 'Sportsboard 3000', file: 'sports.js' },
  { id: 'kaleido', name: 'Kaleidoscope', file: 'kaleido.js' },
  { id: 'spacecam', name: 'Deep Space Cam', file: 'spacecam.js' },
  { id: 'shop', name: 'HyperMall Live', file: 'shop.js' },
  { id: 'cctv', name: 'CCTV Night Watch', file: 'cctv.js' },
  { id: 'slime', name: 'Slime Lab', file: 'slime.js' },
  { id: 'kitchen', name: 'Kitchen Science Club', file: 'kitchenscience.js' },
  { id: 'duckdebug', name: 'Rubber Duck Debugging', file: 'rubberduck.js' },
  { id: 'onetool', name: 'One Tool, Ten Uses', file: 'onetool.js' },
  { id: 'micromyst', name: 'Micro-Mysteries', file: 'micromystery.js' },
  { id: 'traveldesk', name: 'The Tiny Travel Desk', file: 'traveldesk.js' },
  { id: 'fixit', name: 'Fix-It ASMR', file: 'fixit.js' },
  { id: 'patents', name: "History's Weird Patents", file: 'weirdpatents.js' },
  { id: 'futurearch', name: 'Future Archaeology', file: 'futurearch.js' },
  { id: 'circsafari', name: 'Circuit Safari', file: 'circuitsafari.js' },
  { id: 'speedcook', name: 'Speed-Run Cooking', file: 'speedcook.js' },
  { id: 'coffeetimer', name: 'Coffee Timer Radio', file: 'coffeetimer.js' },
  { id: 'rainradio', name: 'Rainy Window Radio', file: 'rainradio.js' },
  { id: 'ufohotline', name: 'Small Town UFO Hotline', file: 'ufohotline.js' },
  { id: 'origami', name: 'Origami After Hours', file: 'origami.js' },
  { id: 'tidydesk', name: 'Tidy Desk Reset', file: 'tidydesk.js' },
  { id: 'workclock', name: 'Minimalist Workout Clock', file: 'workoutclock.js' },
  { id: 'robotzoo', name: 'Robot Petting Zoo', file: 'robotzoo.js' },
  { id: 'foleylab', name: 'Studio Foley Lab', file: 'foleylab.js' },
  { id: 'timetable', name: 'Railway Timetable ASMR', file: 'timetable.js' },
  { id: 'subwaystories', name: 'Subway Map Stories', file: 'subwaystories.js' },
  { id: 'miniworlds', name: 'Found Footage: Miniature Worlds', file: 'miniworlds.js' },
  { id: 'packetsfm', name: 'Packet Sniffer FM', file: 'packetsnifferfm.js' },
  { id: 'nightsignals', name: 'Night Signals', file: 'nightsignals.js' },
];
