export const CHANNELS = [
  { id: 'synthwave', name: 'Synthwave Drive', file: 'synthwave.js' },
  { id: 'traveldesk', name: 'The Tiny Travel Desk', file: 'traveldesk.js' },
  { id: 'nightmarket', name: 'Neon Night Market Ledger', file: 'nightmarket.js' },
  { id: 'packetsfm', name: 'Packet Sniffer FM', file: 'packetsnifferfm.js' },
  { id: 'microfilm', name: 'Microfilm Archive Reader', file: 'microfilm.js' },
  { id: 'lighthouse', name: 'Tiny Lighthouse Watch', file: 'lighthousewatch.js' },
  { id: 'kitchen', name: 'Kitchen Science Club', file: 'kitchenscience.js' },
  { id: 'mailroomtube', name: 'Mailroom Tube Network', file: 'mailroomtube.js' },
  { id: 'sandtable', name: 'Sand Table Cartography', file: 'sandtable.js' },
  { id: 'forgeanvil', name: 'Forge & Anvil Rhythm', file: 'forgeanvil.js' },
  { id: 'futurearch', name: 'Future Archaeology', file: 'futurearch.js' },
  { id: 'matrix', name: 'Terminal Rain', file: 'matrix.js' },
  { id: 'orbits', name: 'Orbital Desktoy', file: 'orbits.js' },
  { id: 'foleylab', name: 'Studio Foley Lab', file: 'foleylab.js' },
  { id: 'elevatorpanel', name: 'Elevator Control Panel Dreams', file: 'elevatorpanel.js' },
  { id: 'cargomanifest', name: 'Starship Cargo Manifest', file: 'cargomanifest.js' },
  { id: 'subwaystories', name: 'Subway Map Stories', file: 'subwaystories.js' },
  { id: 'circsafari', name: 'Circuit Safari', file: 'circuitsafari.js' },
  { id: 'candlechess', name: 'Candlelit Chess Engine', file: 'candlechess.js' },
  { id: 'dungeoncarto', name: "Dungeon Cartographer's Desk", file: 'dungeoncartographer.js' },
  { id: 'city', name: 'Pixel City Nights', file: 'city.js' },
  { id: 'aquarium', name: 'Midnight Aquarium', file: 'aquarium.js' },
  { id: 'arcadeattract', name: 'Arcade Attract Mode Archives', file: 'arcadeattract.js' },
  { id: 'botblueprint', name: 'Botanical Blueprint Studio', file: 'botanicalblueprint.js' },
  { id: 'fire', name: 'Cozy Fireplace', file: 'fireplace.js' },
  { id: 'neonlaundromat', name: 'Neon Laundromat Spin Cycle', file: 'neonlaundromat.js' },
  { id: 'cavetorch', name: 'Cave Torch Storyboard', file: 'cavetorch.js' },
  { id: 'retroboot', name: 'Retro Boot Sequence', file: 'retroboot.js' },
  { id: 'duckdebug', name: 'Rubber Duck Debugging', file: 'rubberduck.js' },
];
